### ISSUE TITLE
Allow support for non-military time

### ISSUE THREAD

**Issue by ProgrammingParadox** [stranothus/timeSince#1]
It would be nice if the hour could also be non-military, perhaps specified with prefixing it with "N", or suffixing it with "PM" or "AM".

**Comment by stranothus** [comment]
For input? Output is time since, so it wouldn’t make sense to use time of day measurements.

**Comment by ProgrammingParadox** [comment]
For the input of the hour, yes.

**Comment by stranothus** [comment]
Functionality added!
